### ISSUE TITLE
Could you please transfer the package on pypi if you are going to do nothing?

### ISSUE THREAD

**Issue by LucienShui** [papierukartka/timer#1]
Hi

Today I find that [your project timer on pypi](https://pypi.org/project/timer/) is empty, and I like the name timer very much, so I wonder if you can transfer it to me?

**Comment by papierukartka** [comment]
Hello,
Yep, the name's nice and simple. Added you as an owner to the pypi package. Feel free to remove me before linking your package.

**Comment by LucienShui** [comment]
Thanks a lot!
You can be the owner of it forever!
Orz
